services:
  ktor-web-app:
    build: .
    ports:
      -  "8080:8080"
    depends_on:
      - mongo
#    environment:
#      HOST: "mongodb"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass